### ISSUE TITLE
Enhancement: Multiple Ideas for this project

### ISSUE THREAD

**Issue by blos** [user1342/Tweezer#3]
I would like to propose multiple ideas that are worth to implement or at least discuss:

- [x] Use [type hints](https://docs.python.org/3/library/typing.html) for everything (see issue #4)
- [x] Use [poetry](https://python-poetry.org/) for dependency management (and potentially packaging for the future) (see issue #5)
- [x] Testing (see issue #6) 
- [x] Some refactoring, maybe UX design (still mostly undefined, but some ideas can be found below)

----
Probably it would a good idea to extract all the points here into its own issues.
This would help with tracking and merging.
You find some extending arguments below.

Before I start with the implementation, I wanted align those things with you.
So let me know what you think.
----
#### Type Hints
Type Hints will not help anyone reading your code.
Compared to static typed programming languages, such as Java, Python as a dynamically typed language allows things that break things.
Consider this code example:
```python
class A:
  def __init__(self, first_arg, second_arg):
    self.first_arg = first_arg + 1
    self.second_arg = seconds_arg + "_suffix"

class B:
  def __init__(self, first_arg: int, second_arg: str) -> None:
    self.first_arg = first_arg + 1
    self.second_arg = second_arg + "_suffix"
```
Someone not knowing the code of Class A could try to initalize this class as follows
```python
class_a = A(first_arg="something", second_arg=42)
```
This would result in an Error in Execution time.
Ideally this would be caught due to compilation time, however Python let you do such things.
To be fair, the following would be possible as well
```python
class_b = B(first_arg="something", second_arg=42)
```
However, most developers/contributors use IDEs which would hint that something is not right.

#### Poetry
There are currently two ways of installing the dependencies for this project.
The first one is using `pip install -r requirements.txt`.
This installs the modules that Tweezer depends on, however does not install Tweezer itself as usable package.
The consequence of this is that using `import Tweezer` will not work.
Using `pip install .` (being in the root directory of the repository) will install Tweezer properly, such as `import Tweezer` will work.
For this matter the `setup.py` file is utilized.
Note that the latter variation will execute python code for the installing the package.
For reference this was issued in [PEP 518](https://peps.python.org/pep-0518/).

[Poetry](https://python-poetry.org/) is a tool for packaging and dependency management.
In short, poetry pinpoints dependency versions which can help isolate breaking upgrades (in the future) and further building (and potentially publishing) the package is as easy as using `poetry build` or `poetry publish`, which is quite easy and handy way of doing this steps.

#### Testing
Implementing at least a rudimentary test suite would be helpful, since changes may break behaviour.
On the one hand, this is a sign of quality (and thus quality assurance) and on the other hand, this creates trust.
Executing some test is vastly less tiring than reading code and looking for typos, mistakes, vulnerabilities, etc.
The first implmentation of a test suite must not be complex, and would be extended step-by-step.
I think, it can only be gained from a test suite.

#### Some refactoring, maybe UX design
- README: Installation instructions are a bit unclear to me. I had some issues installing the package and its dependencies at first. I knew, which steps are necessary only from my experience of other projects so far. I would like to add some more details to the README, just make things a little more clearer. -> solved through #5 
- UX Design: When executing the example that is descibed in the README, I had to wait quite some time while Ghidra decompiled the binary. I had no idea if Tweezer got stuck of is still running. I would propose a small progessbar indicating that it is still running or at least some console output that give some sort of warning, that this can take a minute.
- Some refactoring: For this point, I will open new issues for clustered and different propositions.

**Comment by blos** [comment]
@user1342 If you want, you can assign this issue to me ^^

I'll update this issue with intermediate updates then.

**Comment by user1342** [comment]
Great, as you said. It'll make sense to break it down into multiple issues.

**Comment by blos** [comment]
Yes indeed.
I think it would be beneficial to use this issues as overview page keeping track of the overall progress.
What do you think?

**Comment by user1342** [comment]
#4 and #5 both approved and committed into Main. Thanks for the changes @blos. All looking very clean! 💪

**Comment by user1342** [comment]
Just catching up with these now. Cheers for your work and interest in Tweezer on these enhancements and changes!
